version: '3'

services:
  app:
    container_name: my_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: my_db
    image: mongo:4.0.3
    ports:
      - 27018:27017
    volumes:
      - ./data/db:/data/db
